import { bundle } from "../data/bundle";
import { PageHeader, SectionHeader } from "../components/Layout";
import { Card, Badge } from "../components/ui";
import { formatTimestamp } from "../data/bundle";

const EXTERNAL_LINKS: { label: string; url: string; desc: string }[] = [
  {
    label: "Raw exports (Google Drive)",
    url: "https://drive.google.com/drive/folders/1kkqBC60VPHmdlZfntu3A-8pSKAdIh2Nx?usp=sharing",
    desc: "XLSX 2000–2020 and CSV 2021–2025 V1/V2 source exports.",
  },
  {
    label: "Schema explorer UI",
    url: "https://philgeps.simple-systems.dev/about/schema",
    desc: "Upstream schema browser at philgeps.simple-systems.dev.",
  },
  {
    label: "PS-DBM OCDS templates",
    url: "https://ocds.simple-systems.dev/p/mphilgeps/overview",
    desc: "PS-DBM v0.91 OCDS mapping templates.",
  },
  {
    label: "OCDS 1.1.5 standard",
    url: "https://standard.open-contracting.org/",
    desc: "Open Contracting Data Standard documentation.",
  },
];

export function AboutPage() {
  const meta = bundle.metadata;
  return (
    <>
      <PageHeader
        title="About & sources"
        subtitle="This webapp is a read-only renderer of the mapping artifacts in the philgeps_schema_analysis repository. It bundles no data of its own — regenerate the bundle to refresh."
      />

      <SectionHeader title="What this app shows" />
      <div className="card-grid cols-2">
        <Card>
          <div className="card-title">Layered reference</div>
          <div className="card-body">
            Four layers, each with its own page: raw exports → schema analysis (S1–S5) → canonical
            fields ({bundle.summary.canonical_field_count} fields) → OCDS 1.1.5 staged paths. The
            canonical layer is the Rosetta stone that lets any year's export speak the same
            vocabulary.
          </div>
        </Card>
        <Card>
          <div className="card-title">Live data, no server</div>
          <div className="card-body">
            The app imports a single bundled JSON (<code>app/src/data/schema_bundle.json</code>)
            generated by <code>scripts/build_schema_field_map.py</code>. There is no backend and no
            runtime fetch — the bundle is compiled into the static site.
          </div>
        </Card>
      </div>

      <SectionHeader title="Bundle metadata" />
      <Card>
        <dl className="kv-list">
          <dt>OCDS template</dt>
          <dd>{meta.ocds_template}</dd>
          <dt>Mapping version</dt>
          <dd>
            <Badge variant="blue">{meta.ocds_mapping_version}</Badge>
          </dd>
          <dt>OCID prefix</dt>
          <dd className="mono">{meta.ocid_prefix}</dd>
          <dt>Schema analysis date</dt>
          <dd className="mono">{meta.schema_analysis_date}</dd>
          <dt>Bundle generated</dt>
          <dd className="mono">{formatTimestamp(meta.generated_at)}</dd>
        </dl>
      </Card>

      <SectionHeader title="Source files" subtitle="The artifacts this bundle is built from." />
      <div className="table-wrap">
        <div className="table-scroll">
          <table className="data-table">
            <thead>
              <tr>
                <th>Artifact</th>
                <th>Path</th>
                <th>Role</th>
              </tr>
            </thead>
            <tbody>
              {SOURCE_FILES.map((s) => (
                <tr key={s.path}>
                  <td>{s.label}</td>
                  <td className="mono">{s.path}</td>
                  <td className="muted">{s.role}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <SectionHeader title="Regenerating the bundle" />
      <Card>
        <div className="card-body">
          From the repository root:
          <pre style={pre}>
            <code>pip install -r requirements.txt{"\n"}python scripts/build_schema_field_map.py</code>
          </pre>
          Or from inside <code>app/</code>:
          <pre style={pre}>
            <code>npm run regen-data</code>
          </pre>
          Then restart the dev server (<code>npm run dev</code>) to pick up the new bundle.
        </div>
      </Card>

      <SectionHeader title="External sources" />
      <div className="card-grid cols-2">
        {EXTERNAL_LINKS.map((l) => (
          <Card key={l.url} interactive>
            <div className="card-title">
              <a href={l.url} target="_blank" rel="noreferrer">
                {l.label} ↗
              </a>
            </div>
            <div className="card-body muted">{l.desc}</div>
          </Card>
        ))}
      </div>
    </>
  );
}

const SOURCE_FILES: { label: string; path: string; role: string }[] = [
  {
    label: "Schema analysis",
    path: "references/PHILGEPS_SCHEMA_ANALYSIS.json",
    role: "S1–S5 evolution tables and semantic grouping",
  },
  {
    label: "Schema mappings",
    path: "config/schema_mappings.yaml",
    role: "Source of truth: source column → canonical field",
  },
  {
    label: "Canonical → OCDS",
    path: "config/canonical_to_ocds.yaml",
    role: "Canonical field → OCDS 1.1 path staging rules",
  },
  {
    label: "Codelist mappings",
    path: "config/ocds_codelist_mappings.yaml",
    role: "PhilGEPS labels → OCDS closed codelists",
  },
  {
    label: "Crosswalk",
    path: "references/PHILGEPS_OCDS_CSV_CROSSWALK.md",
    role: "151-row OCDS ↔ PhilGEPS ↔ CSV ↔ canonical join",
  },
  {
    label: "Canonical field map",
    path: "references/PHILGEPS_CANONICAL_FIELD_MAP.json",
    role: "53 canonical fields with per-schema columns",
  },
];

const pre: React.CSSProperties = {
  background: "var(--bg-code)",
  padding: "10px 12px",
  borderRadius: 6,
  margin: "8px 0",
  fontSize: 12.5,
  fontFamily: "var(--font-mono)",
  overflowX: "auto",
};
